### ISSUE TITLE
Error: Cannot find module 'react' when running "npm install" in OS X

### ISSUE THREAD

**Issue by szubtsovskiy** [onefinestay/react-daterange-picker#122]
Hi guys!

I am trying to build react-daterange-picker in OS X and get the following error both when running "npm install" (which invokes "gulp build-dist" in the process) and when running "gulp build-dist-js" directly (after the half-successful "npm install" run):

> > react-daterange-picker@1.0.0 prepublish /Users/szubtsovskiy/Projects/react-daterange-picker
> > gulp build-dist

> [12:40:54] Requiring external module babel-core/register
> module.js:338
>     throw err;
>     ^

> Error: Cannot find module 'react'
>     at Function.Module._resolveFilename (module.js:336:15)
>     at Function.Module._load (module.js:286:25)
>     at Module.require (module.js:365:17)
>     at require (module.js:384:17)
>     at Object.<anonymous> (/Users/szubtsovskiy/Projects/react-daterange-picker/gulpfile.babel.js:7:48)
>     at Module._compile (module.js:434:26)
>     at normalLoader (/Users/szubtsovskiy/Projects/react-daterange-picker/node_modules/babel-core/lib/api/register/node.js:199:5)
>     at Object.require.extensions.(anonymous function) [as .js] (/Users/szubtsovskiy/Projects/react-daterange-picker/node_modules/babel-core/lib/api/register/node.js:216:7)
>     at Module.load (module.js:355:32)
>     at Function.Module._load (module.js:310:12)
> 
> npm WARN EPEERINVALID react-daterange-picker@1.0.0 requires a peer of react@>=0.14.0 but none was installed.
> npm WARN EPEERINVALID react-daterange-picker@1.0.0 requires a peer of react-dom@>=0.14.0 but none was installed.
> npm WARN EPEERINVALID react-addons-pure-render-mixin@0.14.6 requires a peer of react@^0.14.6 but none was installed.
npm WARN EPEERINVALID react-addons-test-utils@0.14.6 requires a peer of react@^0.14.6 but none was installed.
npm WARN EPACKAGEJSON react-daterange-picker@1.0.0 license should be a valid SPDX license expression
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.1.1
npm ERR! npm  v3.3.9
npm ERR! code ELIFECYCLE
npm ERR! react-daterange-picker@1.0.0 prepublish: `gulp build-dist`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-daterange-picker@1.0.0 prepublish script 'gulp build-dist'.
npm ERR! This is most likely a problem with the react-daterange-picker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build-dist
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-daterange-picker
npm ERR! There is likely additional logging output above.

I have tried cleaning npm cache, installing and uninstalling gulp globally (in a hope for some caching issue somewhere). I am using Babel in another project but it is not installed globally.
Did you see this before? Could you please point me where to look to resolve this? Thanks!

**Short summary:**
Node version: 4.1.1
NPM version: 3.3.9
OS X version: 10.11.2

**Comment by szubtsovskiy** [comment]
react and react-dom are peer dependencies and therefore had to exist before running npm install. May be it is worth mentioning in README.
