### ISSUE TITLE
Im getting error

### ISSUE THREAD

**Issue by doronnimrod** [onefinestay/react-daterange-picker#64]
```
TypeError: undefined is not a function
    at [object Object].getEnabledRange (/src/node_modules/react-daterange-picker/dist/DateRangePicker.js:183:32)
    at [object Object].getInitialState (/src/node_modules/react-daterange-picker/dist/DateRangePicker.js:174:26)
    at new Constructor (/src/node_modules/react/lib/ReactClass.js:853:54)
    at [object Object].ReactCompositeComponentMixin.mountComponent (/src/node_modules/react/lib/ReactCompositeComponent.js:135:16)
    at Object.ReactReconciler.mountComponent (/src/node_modules/react/lib/ReactReconciler.js:38:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/src/node_modules/react/lib/ReactMultiChild.js:192:44)
    at ReactDOMComponent.Mixin._createContentMarkup (/src/node_modules/react/lib/ReactDOMComponent.js:289:32)
    at ReactDOMComponent.Mixin.mountComponent (/src/node_modules/react/lib/ReactDOMComponent.js:199:12)
    at Object.ReactReconciler.mountComponent (/src/node_modules/react/lib/ReactReconciler.js:38:35)
    at [object Object].ReactCompositeComponentMixin.mountComponent (/src/node_modules/react/lib/ReactCompositeComponent.js:247:34)
```

Im getting this error , on my production , server .
Env 
Running on Ubunut 14 Docker  Ubuntu 14.
Node ver 12.4
React 13 .
NODE_ENV=production ,
NODE_PATH=./src.
babbel.js

i have no clue , what is the problem. some how moment-range module  doesn't have .range fn .

```
 inside getEnabledRange() , moment obj doesnt have .range fn 
```

on my dev machine everything works as expected

**Comment by AlanFoster** [comment]
@doronnimrod Is this error still present in v0.12.2 ?

**Comment by AlanFoster** [comment]
Closing this issue as there is not enough detail, and it may be fixed in the latest release. Please raise a new issue if it is still occurring for you :+1:
